### ISSUE TITLE
Publish to PyPi

### ISSUE THREAD

**Issue by baseplate-admin** [OtherBarry/django-ninja-decorators#1]
Hi,

is it possible to publish this to PyPi as a means for functionality till `django-ninja#604` gets merged

**Comment by OtherBarry** [comment]
Hi @baseplate-admin ,

I had planned on cleaning up and fleshing out this repo, with the eventual goal of publishing it on PyPi (and also making the changes to get #604 merged).

Unfortunately I've recently been working on embedded software and haven't quite had the time/motivation to work on web stuff.

If you want to PR in any changes, I'd be happy to take a look at them, otherwise hopefully I'll get to it in the next month or two.

Also, thanks for the work you've been putting in recently trying to get django-ninja into shape. I'm keen to help out once I'm back on the web side of things.

**Comment by baseplate-admin** [comment]
> I had planned on cleaning up and fleshing out this repo, with the eventual goal of publishing it on PyPi (and also making the changes to get #604 merged).

Yep sounds good

> Unfortunately I've recently been working on embedded software and haven't quite had the time/motivation to work on web stuff.
 
Ah i see. No worries :D.


> If you want to PR in any changes, I'd be happy to take a look at them, otherwise hopefully I'll get to it in the next month or two.

Unfortunately Vitalik is not available at this point. I did a Pull Request but due to the [lack of response](https://github.com/vitalik/django-ninja/pull/719) i made my own [pypi package](https://pypi.org/project/ninja-put-patch-file-upload-middleware/) ( as it was a release blocker for us ) and published it.

> Also, thanks for the work you've been putting in recently trying to get django-ninja into shape. I'm keen to help out once I'm back on the web side of things.

About this, I have negative opinion at this point on `django-ninja`. Things are not looking good on the internet because of `django-ninja`'s lack of maintenance. Even a django developer commented on something that i have no answer to.. Since i use `django-ninja` on a production basis. I might fork the project and patch upstream ( which i don't want to do ).


---

All in all thanks :D For your work on this repo and for helping out with some stuffs over at `django-ninja`
